name: ademicon_app
description: Aplicativo ADEMICON Londrina
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Núcleo
  supabase_flutter: ^2.10.3
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1

  # Offline-first e utilidades
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.4
  path_provider: ^2.1.4
  url_launcher: ^6.3.2
  mask_text_input_formatter: ^2.9.0
  internet_connection_checker_plus: ^2.5.1
  email_validator: ^2.1.17
  csv: ^6.0.0

  # Arquivos/Compartilhamento
  open_file: ^3.5.10
  share_plus: ^10.1.4
  file_selector: ^1.0.4

  # Notificações e fuso horário
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1

  badges: ^3.1.2

  characters: ^1.4.0

  fl_chart: ^0.68.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Linha_Lateral.png
    - assets/Logo.png
    - .env
